FROM node:20-alpine AS build

WORKDIR /app
ENV CI=true
ENV NODE_OPTIONS=--max-old-space-size=4096

COPY frontend/package*.json /app/
RUN npm ci --no-audit --no-fund

COPY frontend /app
RUN npm run build

FROM nginx:1.27-alpine

COPY docker/frontend/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
