"""Some Updates

Revision ID: 056c166fc2f6
Revises: bc4d59a9b63e
Create Date: 2025-08-28 11:06:44.151216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '056c166fc2f6'
down_revision = 'bc4d59a9b63e'
branch_labels = None
depends_on = None


def upgrade():
    inspector = sa.inspect(op.get_bind())
    order_item_columns = {col["name"] for col in inspector.get_columns("order_items")}

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        if 'printed_quantity' not in order_item_columns:
            batch_op.add_column(sa.Column('printed_quantity', sa.Numeric(precision=5, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    inspector = sa.inspect(op.get_bind())
    order_item_columns = {col["name"] for col in inspector.get_columns("order_items")}

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        if 'printed_quantity' in order_item_columns:
            batch_op.drop_column('printed_quantity')

    # ### end Alembic commands ###
