"""Print

Revision ID: 3d52a2333b20
Revises: 056c166fc2f6
Create Date: 2025-08-29 00:47:19.730813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d52a2333b20'
down_revision = '056c166fc2f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('print_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('error_message', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('printed_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('station_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('print_jobs', schema=None) as batch_op:
        batch_op.alter_column('station_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('printed_at')
        batch_op.drop_column('error_message')
        batch_op.drop_column('type')

    # ### end Alembic commands ###
