"""snap shot update

Revision ID: 65d91c203f38
Revises: 986ce072cf7d
Create Date: 2025-09-27 08:17:20.856117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65d91c203f38'
down_revision = '986ce072cf7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('station_stock_snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sold_quantity', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('remaining_quantity', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('station_stock_snapshots', schema=None) as batch_op:
        batch_op.drop_column('remaining_quantity')
        batch_op.drop_column('sold_quantity')

    # ### end Alembic commands ###
