"""Inventory Model fix

Revision ID: 723cf52eb22a
Revises: 422ef1bcba67
Create Date: 2025-09-26 19:55:25.692304

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '723cf52eb22a'
down_revision = '422ef1bcba67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_consumptions')
    op.drop_table('daily_stock_snapshots')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_stock_snapshots',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('station_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('inventory_item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('starting_quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], name=op.f('daily_stock_snapshots_inventory_item_id_fkey')),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name=op.f('daily_stock_snapshots_station_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('daily_stock_snapshots_pkey'))
    )
    op.create_table('stock_consumptions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('station_stock_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('inventory_item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_item_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], name=op.f('stock_consumptions_inventory_item_id_fkey')),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], name=op.f('stock_consumptions_order_item_id_fkey')),
    sa.ForeignKeyConstraint(['station_stock_id'], ['station_stock.id'], name=op.f('stock_consumptions_station_stock_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('stock_consumptions_pkey'))
    )
    # ### end Alembic commands ###
