"""empty message

Revision ID: 8e926fe32e87
Revises: e91f0a6b4c2d
Create Date: 2026-03-08 13:33:00.180377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e926fe32e87'
down_revision = 'e91f0a6b4c2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.alter_column('serving_unit',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'unit'::character varying"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.alter_column('serving_unit',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'unit'::character varying"))

    # ### end Alembic commands ###
