"""Remove name column from users

Revision ID: 953ade75b174
Revises: f06390976849
Create Date: 2025-08-17 22:38:06.612998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '953ade75b174'
down_revision = 'f06390976849'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
