"""snap shot

Revision ID: 986ce072cf7d
Revises: addc0623dce7
Create Date: 2025-09-27 07:38:19.934736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '986ce072cf7d'
down_revision = 'addc0623dce7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('station_stock_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('inventory_item_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('start_of_day_quantity', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'inventory_item_id', 'snapshot_date', name='uq_station_item_date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('station_stock_snapshots')
    # ### end Alembic commands ###
