"""snap shot added quantity

Revision ID: aa1ce94be82c
Revises: e4c4bcf04ed0
Create Date: 2025-10-04 04:41:16.305181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa1ce94be82c'
down_revision = 'e4c4bcf04ed0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('station_stock_snapshots', schema=None) as batch_op:
        batch_op.alter_column('added_quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('station_stock_snapshots', schema=None) as batch_op:
        batch_op.alter_column('added_quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)

    # ### end Alembic commands ###
