"""Sync

Revision ID: ad74b06a829a
Revises: deb409e10174
Create Date: 2025-08-19 22:03:43.866632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad74b06a829a'
down_revision = 'deb409e10174'
branch_labels = None
depends_on = None


def upgrade():
    inspector = sa.inspect(op.get_bind())
    menu_item_columns = {col["name"] for col in inspector.get_columns("menu_items")}
    order_item_columns = {col["name"] for col in inspector.get_columns("order_items")}
    if "vip_price" in menu_item_columns and "vip_price" in order_item_columns:
        return

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        if "vip_price" not in menu_item_columns:
            batch_op.add_column(sa.Column('vip_price', sa.Float(), nullable=True))
        batch_op.alter_column('subcategory_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('menu_items_subcategory_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'subcategories', ['subcategory_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        if "vip_price" not in order_item_columns:
            batch_op.add_column(sa.Column('vip_price', sa.Numeric(precision=10, scale=2), nullable=True))

    with op.batch_alter_table('subcategories', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('subcategories_category_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    return

    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subcategories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('subcategories_category_id_fkey'), 'categories', ['category_id'], ['id'])
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('vip_price')

    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('menu_items_subcategory_id_fkey'), 'subcategories', ['subcategory_id'], ['id'])
        batch_op.alter_column('subcategory_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('vip_price')

    # ### end Alembic commands ###
