"""Inventory Model Backroll

Revision ID: addc0623dce7
Revises: 8d2c526c6c87
Create Date: 2025-09-27 06:07:07.395349

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'addc0623dce7'
down_revision = '8d2c526c6c87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_sales')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_sales',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('inventory_item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('station_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], name=op.f('stock_sales_inventory_item_id_fkey')),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name=op.f('stock_sales_station_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('stock_sales_pkey'))
    )
    # ### end Alembic commands ###
