"""Status added to Inventory

Revision ID: b8cca316001a
Revises: 3fa926ee9dc5
Create Date: 2025-09-24 16:28:06.584284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8cca316001a'
down_revision = '3fa926ee9dc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    with op.batch_alter_table('stock_transfers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_transfers', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('stock_purchases', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
