"""Print

Revision ID: bc4d59a9b63e
Revises: 98a34336b6ef
Create Date: 2025-08-27 07:01:48.398028

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bc4d59a9b63e'
down_revision = '98a34336b6ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('printed_quantity', sa.Numeric(precision=5, scale=2), nullable=True))

    with op.batch_alter_table('print_jobs', schema=None) as batch_op:
        batch_op.drop_column('png_generated')
        batch_op.drop_column('png_paths')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('print_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('png_paths', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('png_generated', sa.BOOLEAN(), autoincrement=False, nullable=True))

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('printed_quantity')

    # ### end Alembic commands ###
