"""Some Updates

Revision ID: deb409e10174
Revises: bfd4308740b5
Create Date: 2025-08-19 12:30:27.339170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deb409e10174'
down_revision = 'bfd4308740b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.alter_column('subcategory_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('menu_items_subcategory_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'subcategories', ['subcategory_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vip_price', sa.Numeric(precision=10, scale=2), nullable=True))

    with op.batch_alter_table('subcategories', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('subcategories_category_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subcategories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('subcategories_category_id_fkey'), 'categories', ['category_id'], ['id'])
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('vip_price')

    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('menu_items_subcategory_id_fkey'), 'subcategories', ['subcategory_id'], ['id'])
        batch_op.alter_column('subcategory_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
