"""snap shot added quantity

Revision ID: e4c4bcf04ed0
Revises: 65d91c203f38
Create Date: 2025-10-04 04:39:36.536248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4c4bcf04ed0'
down_revision = '65d91c203f38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('station_stock_snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('added_quantity', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('station_stock_snapshots', schema=None) as batch_op:
        batch_op.drop_column('added_quantity')

    # ### end Alembic commands ###
