"""Waiter PIN added Categories and Subcategories 

Revision ID: f06390976849
Revises: 3a732e6be564
Create Date: 2025-08-17 16:17:52.611328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f06390976849'
down_revision = '3a732e6be564'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('subcategories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'name', name='uq_subcategory_name_per_category')
    )
    op.create_table('waiter_table_assoc',
    sa.Column('waiter_id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.ForeignKeyConstraint(['waiter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('waiter_id', 'table_id')
    )
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subcategory_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'subcategories', ['subcategory_id'], ['id'])

    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('tables_waiter_id_fkey'), type_='foreignkey')
        batch_op.drop_column('waiter_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pin_hash', sa.Text(), nullable=True))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('pin_hash')

    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('waiter_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('tables_waiter_id_fkey'), 'users', ['waiter_id'], ['id'])

    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('subcategory_id')

    op.drop_table('waiter_table_assoc')
    op.drop_table('subcategories')
    op.drop_table('categories')
    # ### end Alembic commands ###
